siteorigin/siteorigin-unwind

- functions.php
- inc/extras.php
- sass/layout/_general.scss
- sass/site/primary/_posts-and-pages.scss
- search.php
- style.css
- template-parts/content-search.php
- template-parts/content.php
used filter to modify excerpt_more.
Added image size for search posts.
> Modified and styled search results

- sass/layout/_content-sidebar.scss
- sass/navigation/_menus.scss
- sass/site/primary/_comments.scss
- sass/site/primary/_posts-and-pages.scss
- style.css
Some minor fixes to improve responsiveness in the post layout and search results.
> Layout fixes

- sass/navigation/_menus.scss
- style.css
Changed styling navigation from position to visibility & opacity.
Added simple animation to the dropdowns.
> Updated styling for main navigation

- functions.php
- woocommerce/functions.php
Added functions, scss and js files
> Setup WooCommerce

- functions.php
- header.php
- inc/settings.php
Implemented enhancement #12 
Updated settings submodule.
Removed the header sidebar.
Used WB's social buttons widget.
> Header social profiles

- functions.php
- inc/template-tags.php
> Implemented custom logo feature

- 404.php
- footer.php
- functions.php
- header.php
- inc/extras.php
- inc/settings.php
- inc/template-tags.php
- sass/layout/_page-settings.scss
- sass/site/header/_masthead.scss
- search.php
- sidebar.php
- style.css
- template-parts/content-page.php
- template-parts/content-single.php
Implemented enhancement #17 
- Added page settings
- Added page settings body classes
- Implemented page setting in templates
- Added styling as necessary
@Misplon please test and let me know if anything isn't working. Thanks.
> Page settings

- js/woocommerce.js
- sass/woocommerce/_archive.scss
- woocommerce.css
- woocommerce/functions.php
Styled product archive ordering select.
Styled product archive result count.
Styled archive pagination. @Misplon do you think we should add some hover styles?
> Product archive elements

- js/unwind.js
- js/woocommerce.js
Checked if flexslider exists before calling it.
> Checked for flex slider before calling it

- js/unwind.js
> Disable scrolling when fullscreen search is open

- js/unwind.js
> If mobile menu is clicked, close search, open mobile menu

- inc/settings.php
- inc/template-tags.php
Implemented enhancement #45 
Added and implemented settings to display date, categories, comments link and tags.
> Added blog settings

- inc/settings.conf.php
- inc/settings.php
@Misplon this should get the details font working.
> Fixed incorrectly mapped SASS variable

- inc/template-tags.php
- template-parts/content-gallery.php
> Added permalink to date for archive pages

- inc/settings.php
- sass/media/_home-slider.scss
- style.css
- template-parts/featured-slider.php
Implemented enhancement #71
Added setting to enable image overlay.
Added class to `.slide-content` when enabled.
Used `rgba( 0, 0, 0, 0.5 )`.
> SliderOpacity

- sass/woocommerce/_buttons.scss
- sass/woocommerce/_product.scss
- woocommerce.css
Fixed bug #74 and #75.
@AlexGStapleton can you please check if #74 is sorted out. Thanks.
Also styled WC message on Product posts.
**Old** 
**New**
> Wc styling fix

- header.php
- inc/settings.php
> Added setting to disable search button in masthead

- inc/settings.php
- woocommerce/quick-view.php
- woocommerce/template-tags.php
Implemented enhancement #66 
Added WC settings only if plugin is active.
Added setting to disable quick view button ( defaults to true )
Implemented the setting
> Woo settings

- sass/media/_home-slider.scss
- style.css
Fixed bug #86 
Seems to be a Chrome only bug. Please let me know if any other browser has the problem. Thanks
> Fixed overlay lag when navigating to previous slide

- functions.php
- loops/loop-slider.php
- sass/media/_home-slider.scss
- style.css
- template-parts/featured-slider.php
Implemented enhancement #86 
Added template for post slider.
Enqueuing flexslider assets globally.
We can revert back to the conditional statement after https://github.com/siteorigin/siteorigin-panels/issues/282 is sorted out.
> Slider loop

- inc/settings.php
- sass/navigation/_menus.scss
- style.css
Implemented enhancement #84 
Added setting to adjust mobile menu.
Used `siteorigin_settings_custom_css` filter to add necessary CSS.
Removed breakpoint associated CSS from style.css.
@Misplon please test. Let me know if you come across any issues. :)
> Added setting to adjust mobile menu breakpoint

- inc/extras.php
- inc/settings.php
- sass/layout/_layout.scss
- sass/woocommerce/_archive.scss
- sass/woocommerce/_layout.scss
- style.css
- woocommerce.css
Implemented enhancement #89 
Added settings to change position of main and shop sidebars.
Added necessary CSS.
@Misplon I also adjusted the Ordering dropdown CSS as we had discussed on slack. Please test. Thanks.
> Sidebar placement

- inc/settings.php
- template-parts/content.php
> Added setting to replace content with excerpt in archives

- functions.php
- header.php
- sass/site/header/_masthead.scss
- style.css
Implemented enhancement #83 
Added sidebar called **Masthead**.
Logo and description are replaced with this sidebar if it isn't empty.
Added margin above and below the sidebar.
> Added masthead sidebar to replace the logo

- inc/template-tags.php
- template-parts/content-gallery.php
- template-parts/content-image.php
- template-parts/content-video.php
Applied excerpt setting to different post formats
> Blog loop excerpt

- js/unwind.js
Fixed bug #105 
Mobile menu cart link will only appear once.
Fixed sub-menu dropdown.
> Mobile menu fixes

- sass/navigation/_menus.scss
- sass/woocommerce/_cart.scss
- style.css
- woocommerce.css
Implemented enhancement #112 
Aligned shopping bag alongside max mega menu.
Fixed CSS for submenus in max mega menu.
> Added support for max mega menu

- js/woocommerce.js
- sass/woocommerce/_archive.scss
- woocommerce.css
Fixed bug #109
The featured image gets replaced with the variation image.
> Display variation images for wc products

- inc/settings.php
- sass/woocommerce/_cart.scss
- woocommerce.css
> Updated settings custom CSS

- js/woocommerce.js
- sass/woocommerce/_archive.scss
- sass/woocommerce/_cart.scss
- sass/woocommerce/_product.scss
- sass/woocommerce/_quickview.scss
- style.css
- woocommerce.css
- woocommerce/functions.php
- woocommerce/quick-view.php
Fixed bug #78 
Styled the select box.
Fixed the variations field in the quick view modal.
Updated the quick view styling.
Styled variable product in mini cart dropdown.
> Wc variations styled

- sass/navigation/_menus.scss
- style.css
> Fixed bug with social media widget

- template-parts/content-single.php
- template-parts/content.php
> centre align post thumbnails

- inc/template-tags.php
Added support for Jetpack related posts
Changed the headline to match our design.
Will replace our related posts if activated.
> Added compatibility with jetpack related posts

- woocommerce/single-product/product-image.php
- woocommerce/single-product/product-thumbnails.php
- woocommerce/single-product/review-meta.php
Our templates are all good. Updated version numbers.
> Updated wc template version number

- sass/woocommerce/_archive.scss
- woocommerce.css
@Misplon please test. Let me know if it does not work.. Thanks
> Styled wc loop read more button

- sass/site/header/_masthead.scss
- style.css
> Added masthead bottom margin on home page

- js/unwind.js
- sass/site/header/_masthead.scss
- style.css
- template-parts/header-1.php
- template-parts/header-2.php
- template-parts/header-3.php
- template-parts/header-4.php
Fixed bug #135 
@Misplon please test. Thanks
> Made navigation sticky instead of top bar in masthead

- js/woocommerce.js
> Close quickview with escape key

- sass/site/header/_masthead.scss
- style.css
Fixed bug #140 
@Misplon please test. thanks
> Header update

- sass/site/header/_masthead.scss
- sass/woocommerce/_archive.scss
- sass/woocommerce/_cart.scss
- style.css
- woocommerce.css
Fixed bug #143
@Misplon please test. Thanks
> Added max height to masthead mini cart

- js/unwind.js
Implemented enhancement #145 
@Misplon & @AlexGStapleton  please test this out. Let me know how it works. Thanks
> Placed sticky sentinel before the top bar

- sass/navigation/_menus.scss
- style.css
> Changed position of menu dropdown for header 4

- inc/template-tags.php
- sass/site/primary/_posts-and-pages.scss
- style.css
Implemented enhancement #157 
Added function `siteorigin_unwind_three_categories` which displays the first 3 categories.
> Blog cats limit

- inc/template-tags.php
> Remove only first video from post content

- inc/settings.php
- loops/loop-blog-left-info.php
- sass/site/primary/_posts-and-pages.scss
- style.css
- template-parts/content-left-info.php
Added the left info blog layout
@Misplon please check out the responsive view. I have made it similar to the default template. Thanks
> Left info blog layout

- sass/woocommerce/_cart.scss
- woocommerce.css
> Header Layout 4: Swing mini-cart to the left

- sass/site/primary/_posts-and-pages.scss
- style.css
- template-parts/content-alternate.php
- template-parts/content-grid.php
- template-parts/content-offset.php
Implemented enhancement #162 
Fixed bug #168 
Added post formats to the grid and alternate blog layouts.
Implemented all settings to the offset layout.
@Misplon please test before merging. Thanks
> Blog layout update

- inc/settings.php
- sass/site/primary/_posts-and-pages.scss
> Updated settings CSS

- inc/settings.php
- js/unwind.js
- loops/loop-blog-masonry.php
- sass/site/primary/_posts-and-pages.scss
- style.css
- template-parts/content-masonry.php
Implemented enhancement #169 
Added masonry option to settings.
Added loop and template file for masonry layout.
Added styling.
Used 'jquery-masonry' core script.
@Misplon please test. Also check out responsive states. Thanks.
> Added masonry blog layout

- sass/woocommerce/_archive.scss
- woocommerce.css
Fixed bug #159 
@Misplon please check. Thanks
> Disabled shop hover buttons for mobile

- header.php
- inc/settings.php
- sass/woocommerce/_layout.scss
- woocommerce.css
- woocommerce/functions.php
- woocommerce/template-tags.php
Fixed bug #185 
Styled notice
moved notice to masthead
removed default action hook
> Adjusted woocommerce store notice

- inc/settings.php
- template-parts/header-1.php
- template-parts/header-2.php
- template-parts/header-3.php
- template-parts/header-4.php
Implemented enhancement #182 
Added page setting.
Only `.top-bar` is displayed when the setting is `false`.
> Added Display Masthead page setting

- js/unwind.js
Appended infinite scroll projects to `#portfolio-loop`
Isotope applys to newly added elements
> Infinite Scroll compatibility with Isotope

- archive.php
- inc/template-tags.php
- loops/loop-portfolio.php
- template-parts/content-portfolio.php
Fixed bug #191 
Fixed bug #192 
Fixed issue with all projects being displayed on archive pages.
> Portfolio fix

- functions.php
- js/woocommerce.js
- sass/woocommerce/_quickview.scss
- style.css
- woocommerce.css
- woocommerce/template-tags.php
Implemented enhancement #70
Modified the template to display all images.
Added JS and CSS for flexslider
@Misplon please let me know if any changes are needed. Thanks.
> Add Gallery to Quick View

- inc/template-tags.php
- style.css
> Added Ellipsis before the read more button

- sass/woocommerce/_product.scss
- woocommerce.css
> Fixed issue with products sold individually

- js/unwind.js
- sass/site/header/_masthead.scss
- style.css
Implemented enhancement #160 
Added animation named `stickyMh` to sticky header. @Misplon I have given it a fade in effect. Please test. Thanks.
> Added animation to sticky masthead

- woocommerce/archive-product.php
- woocommerce/checkout/form-checkout.php
- woocommerce/product-searchform.php
@Misplon merge after WC is updated to 3.3.0
> Updated WC functions to version 3.3.0

- functions.php
The file is minified, it's just not output. This PR will ensure it is.
> Ensure siteorigin-unwind-skip-link-focus-fix is minified

- inc/jetpack.php
- loops/loop-portfolio.php
Fixed bug #228 
@Misplon please test.Thanks
> fixed pagination for portfolio archives

- js/unwind.js
- loops/loop-blog-portfolio.php
- sass/site/primary/_posts-and-pages.scss
- style.css
- template-parts/content-blog-portfolio.php
> Added blog with portfolio template loop

- inc/settings.php
This PR will ensure Mobile Menu Breakpoint can update without reloading the customizer
> Mobile Menu: Ensure Mobile Menu Breakpoint can update without reloading the customizer p2

- js/unwind.js
- sass/navigation/_menus.scss
- style.css
This is a copy of siteorigin/siteorigin-corp#63 for Unwind.
> Allow mobile users to open sub menu when mobile menu is disabled

- searchform.php
- template-parts/header-1.php
- template-parts/header-2.php
- template-parts/header-3.php
- template-parts/header-4.php
- template-parts/searchform-fullscreen.php
This PR is a version of siteorigin/siteorigin-north#360 for Unwind.
> Improve Search Label Accessibility

- js/unwind.js
We avoid a few complications not using this function. @AlexGStapleton Please, briefly test for us. I can't see any issues.
> Removed resetMenu function

- footer.php
- inc/settings.php
- inc/template-tags.php
- sass/site/_footer.scss
- style.css
Looks like some PHP spacing fixes made it into this commit. Sorry about that.
> Changed footer separators to hyphens

- inc/template-tags.php
> Exclude the logo from Smush Lazy Loading

- inc/template-tags.php
> Merge Lazy Load Logo Exclusion functions into single function

- inc/settings.php
- sass/navigation/_menus.scss
- sass/site/header/_masthead.scss
- sass/woocommerce/_cart.scss
- style.css
- template-parts/header-1.php
- template-parts/header-2.php
- template-parts/header-3.php
- template-parts/header-4.php
- woocommerce.css
This PR ensures that the contents of the menu bar are always vertically aligned. It's a change in method and a bit of a refactor. This next release won't be backward compatible due to changes in the header PHP files so I guess we'll need to bump the version number to 1.5.
> Ensure menu contents are vertically aligned

- functions.php
- sass/style-editor.scss
- style-editor.css
Resolves https://github.com/siteorigin/siteorigin-unwind/issues/262.
> Fixed Block Editor max-width

- template-parts/header-4.php
Resolves https://github.com/siteorigin/siteorigin-unwind/issues/264.
> Header 4: Don’t display top bar if empty

- sass/woocommerce/_cart.scss
- woocommerce.css
> Set mini-cart count position

- sass/navigation/_menus.scss
- style.css
Resolves https://github.com/siteorigin/siteorigin-unwind/issues/268.
@AlexGStapleton Quick test to see if there are any unintended consequences that I've missed.
> Added nowrap to social icons container

- sass/woocommerce/_cart.scss
- woocommerce.css
- woocommerce/functions.php
> WC: Remove cart_item_image_size to allow for variation images to appear in cart

- inc/extras.php
- inc/settings.php
- sass/woocommerce/_archive.scss
- woocommerce.css
- woocommerce/template-tags.php
> Added an Add to Cart setting

- sass/navigation/_menus.scss
- sass/site/header/_masthead.scss
- style.css
Recent menu enhancements impacted the way multi-line menus are displayed. This PR aims to marginally improve the display of multi-line menus.
To test this PR, add a multi-line-menu using the develop branch then switch to this PR branch to see the difference. Please, test with all four header layouts. Thanks.
> Better accommodate multi-line menus

- js/woocommerce.js
> WC Quick View: Add image change when variations selected

- sass/navigation/_menus.scss
It's possible this change may result in a noticeable difference in spacing so please run some tests to identify if any undesired changes are noticeable.
> Correct invalid CSS

- css/flexslider.css
- js/jquery.flexslider.js
- js/unwind.js
- js/woocommerce.js
> WP 5.6 jQuery changes 

- inc/settings.php
- inc/template-tags.php
Requires https://github.com/siteorigin/settings/pull/67
> Use Settings Lazy Load Exclude Logo

- js/unwind.js
- js/woocommerce.js
JQMIGRATE: jQuery.isFunction() is deprecated
> Replace deprecated $.isFunction()

- js/jquery.flexslider.js
This PR fixes an issue that prevents product gallery navigation via product thumbnails.
> Fix product gallery navigation issue

- build-config.js
Related https://github.com/siteorigin/settings/commit/8e55e505f840d0ddea64e7ed398196ccb88940d7
> Update build config to include chosen in minify

- inc/template-tags.php
- template-parts/content-alternate.php
- template-parts/content-grid.php
- template-parts/content-masonry.php
- template-parts/content-offset.php
- template-parts/content-video.php
Resolve https://github.com/siteorigin/siteorigin-unwind/issues/312
Please test this using:
- The Classic Editor.
- The Block Editor.
- Self Hosted video
- External video
> Video Format: Add Support For SO Video Player Widget
