siteorigin/siteorigin-unwind

inc/template-tags.php, yarpp-template-unwind.php
This filter will allow users to change the date_format.
For example, the following code will allow the user to use the WordPress defined date format:
```
function siteorigin_unwind_use_wp_date_format ( $date_format ) {
return get_option( 'date_format' );
}
add_filter( 'siteorigin_unwind_date_format', 'siteorigin_unwind_use_wp_date_format' );
```
Related to #90.
=> Add filter to allow users to adjust date_format

single.php
This PR adds a function_exists check on sharing_display() as I suspect that function doesn't exist if Jetpack isn't enabled. Plus, [Jetpack recommends doing this](https://jetpack.com/tag/sharedaddy/).
Context:
A user has reported the following error: Fatal error: Call to undefined function sharing_display() in /nas/content/staging/usernamehere/wp-content/themes/siteorigin-unwind/single.php on line 30
I suspect this might be due to them not being able to activate Jetpack at this time (due to mod_auth on WordPress during dev)
=> Jetpack Share: Check to ensure sharing_display() exists

header.php, inc/extras.php, inc/settings.php, inc/template-tags.php, js/unwind.js, sass/navigation/_menus.scss, sass/site/header/_masthead.scss, sass/site/header/_search.scss, sass/woocommerce/_cart.scss, style.css, template-parts/header-1.php, template-parts/header-2.php, template-parts/header-3.php, template-parts/header-4.php, woocommerce.css
Theme now has 4 header designs.
1. Added setting to choose header design. ( labeled **Header 1**, **Header 2**, **Header 3** & **Header 4** )
2. Added function `siteorigin_unwind_main_navigation` in `template-tags.php`. ( outputs main navigation )
3. Moved masthead content to the `template-parts` folder. Added files for all 4 designs.
4. Added class to body depending on header design chosen.
5. Reworked sticky navigation.
6. Updated fullscreen search. ( CSS and JS )
7. Removed Masthead bottom border for homepage.
8. _**Unrelated to the rest of this PR** :  Improved logic to sidebar position body classes_
@Misplon please test. Let me know if I have overlooked any issue. This PR is also fixes  #73.
=> Header designs

template-parts/content-single.php
Brackets require at least PHP 5.4 so on older setups, this error will occur:
Parse error: syntax error, unexpected ‘[‘ in /home/julianpe/public_html/reachingforless.com/wp-content/themes/siteorigin-unwind/template-parts/content-single.php on line 24
=> Changed the_post_thumbnail() parameters to use traditional array

sass/site/header/_masthead.scss
non-existent z-index and display: relative; on `#masthead`resulted in sticky header going behind siteorigin hero widget.
=> Higher masthead z-index

sass/site/header/_masthead.scss
Normal anchor tag and image tag display behavior caused "false" margins below logo images.
=> Fix uneven logo margin

js/unwind.js
Fixed bug #153 
Updated `unwindIsVisible`. Made it more specific for our use case. 
Added `unwindAdminIsVisible`. Check if an element is overlapping the admin bar.
Added logic to get it all working.
@Misplon please test. Thanks.
=> Factored in admin bar for sticky navigation

woocommerce/functions.php
add_to_cart_fragments was deprecated in WC 3 for woocommerce_add_to_cart_fragments. It's just a function rename but this PR will fix it and allow for backwards compatibility.
Copy of siteorigin/siteorigin-north#314
=> WC: Add To Cart deprecated notice fix

inc/template-tags.php
Fixes WC notice:
> Notice: WC_Cart::get_cart_url is deprecated since version 2.5! Use wc_get_cart_url instead
Copy of siteorigin/siteorigin-north#313
=> WC: Fix Cart URL Deprecated Notice Fix

js/unwind.js, sass/navigation/_menus.scss, style.css
Fixed bug #199 
All menu items with dropdowns which have undefined `href` open their dropdown on click.
=> Non link mobile menu opens dropdown on click

inc/template-tags.php, loops/loop-medium-left.php, template-parts/content-alternate.php, template-parts/content-gallery.php, template-parts/content-grid.php, template-parts/content-image.php, template-parts/content-masonry.php, template-parts/content-offset.php, template-parts/content-search.php, template-parts/content-video.php, template-parts/content.php
Fixed bug #207 
The `excerpt_length` and `excerpt_more` filters only work on excerpts that are generated from the content.
Added `siteorigin_unwind_excerpt` function to handle all excerpts. Should be used instead of `the_excerpt`.
Deprecated functions `siteorigin_unwind_excerpt_length` and `siteorigin_unwind_excerpt_more`.
Please test. Thanks.
=> Excerpt length

js/unwind.js
It's great that aria-expanded is present, but it doesn't currently change regardless of state. This PR fixes that. It also allows for # links to correctly open sub menus.
=> Mobile Menu: Update aria-expanded state, allow for # links to open sub menu

js/unwind.js, sass/site/header/_masthead.scss, sass/site/primary/_portfolio.scss, style.css
The sticky menu check previously didn't factor in the admin bar being sticky on desktop, and not sticky on mobile. This resulted in issues as the calculation was written specifically with that in mind.
=> Mobile menu sticky fix

sass/navigation/_menus.scss, style.css
Previously, the Social Icons alignment setting wouldn't do anything. This is okay for the header designs where this everything is on the same line but when the social icons are on a different line to the menu, the alignment options really need to work.
=> Social icons alignment fix for certain header designs

inc/template-tags.php
A user reported an issue with their mobile menu not working in Unwind. Turns out they have previously set a custom mobile menu icon and forgot about it. They then accidentally deleted the mobile menu icon and when this happens, the mobile menu icon doesn't display. This PR accounts for this situation by ensuring the image exists and is actually an image.
=> Account for missing Custom Icon

js/unwind.js
This PR resolves an issue that prevents any JavaScript from being added after [line 221](https://github.com/siteorigin/siteorigin-unwind/blob/1.4.1/js/unwind.js#L221) if a Jetpack Portfolio Loop isn't added to the page.
=> Make Jetpack Portfolio Post Loop check more specific

template-parts/searchform-fullscreen.php, woocommerce/product-searchform.php
This PR replaces site_url() with home_url(). The Site URL can be different to the Home URL as a result of how the user structures their website files. For example, if the user has their files in a separate directory to the root of the domain, the Site URL will be different to the Home URL.
References:
https://github.com/woocommerce/woocommerce/blob/master/templates/product-searchform.php
https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentyseventeen/searchform.php#L15
=> Search Forms: Replace all instances of site_url() with home_url()

sass/woocommerce/_cart.scss, woocommerce.css
Resolves #272.
Ensure you've first recreated the remove button overflow issue in `develop` before switching to this branch.
=> Added mini cart item right padding

js/woocommerce.js, sass/woocommerce/_product.scss, woocommerce.css, woocommerce/functions.php
@AlexGStapleton Using develop, activate https://wordpress.org/plugins/woo-variation-swatches/ and check a product with variations. Check the formatting issues. Then switch to this branch. 
If there is a better way to make the exclusion in the JS file or anything else you see, please, let me know.
=> Woo variation swatches

inc/extras.php, sass/woocommerce/_archive.scss, woocommerce.css, woocommerce/functions.php
This should have been split up into smaller PR's, please, bear with me. Sorry for the hassle.
**Conditionally load the WooCommerce JavaScript file:**
* If we’re on a known WooCommerce page.
* If we're on the cart page.
* If the page has a product shortcode.
**Added an overlay class in place of the add to cart class**
This is to ensure the green overlay is added for WooCommerce archive pages and WooCommerce product shortcodes if both or one of the buttons is present, Add to Cart and or Quick View.
**Reorder selectors**
This commit made it was into the PR accidentally.
**Added class for when one button is present**
The goal here is to vertically center the Add to Cart or Quick View button if it's the only button present. The method we're using in Corp `a:first-child:nth-last-child(2) ~ a` …
=> WooCommerce Product Overlay Improvements

inc/template-tags.php
Resolve https://github.com/siteorigin/siteorigin-unwind/issues/289
The static front page doesn't set the paged query var, instead it uses page. `previous/next_posts_link` doesn't check if `page` is set and only checks for `paged`.
This isn't an issue with our themes due to those all using `paginate_links)`. This also isn't an issue with the post loop itself, not the pagination, as it accounts for this - try manually changing the page URL and you'll notice the posts change as expected.
=> Account for Post Loop being used on static front page

inc/template-tags.php
Related siteorigin/siteorigin-north#397
- Includes WP 5.5 Lazyload
- Restored LiteSpeed Lazy Load Compatibility
Unwind doesn't use the old Jetpack Lazy Load logo exclusion code.
=> Update Logo Lazy Load Exclusion

sass/woocommerce/_product.scss, woocommerce.css, woocommerce/functions.php
This PR reverts commit 372f37e18a8ea09ede8a500c4bb3c172d646de1c which was to resolve https://github.com/siteorigin/siteorigin-unwind/issues/274. The problem is that change resulted in the gallery area height being based on the largest image. Depending on the user's images this can sometimes result in a large amount of spacing. For example:
The last commit resolves the original issue by moving the WC JS file to the footer.
=> Set WC JS to load in footer to prevent spacing issue

template-parts/content-alternate.php
Resolve the above issue by only loading the sized featured image if the page layout in use is the default.
=> Don’t size the featured image unless the default page layout is in use

inc/template-tags.php
@AlexGStapleton I don't know why this space was there, maybe from another theme where the function was originally written? There are several combos to test. Items to consider:
* With and without footer text.
* With and without privacy policy link.
* With and without footer attribution link.
All seems fine to me, if you could confirm, that would be best.
Cheers
=> Removed footer text space

sass/woocommerce/_product.scss, woocommerce.css
Styling issue for qty buttons in WCTB. To check those changes ensure buttons are properly formatted within WCTB and outside of the WCTB on a normal page.
Issue two:
=> Fix WooCommerce qty button styling in WCTB

js/unwind.js
This PR modifies the masonry template to maintain [horizontalOrder](https://masonry.desandro.com/options.html#horizontalorder). This ensures that the posts are always output in the correct order.
=>  Masonry: Maintain horizontalOrder

woocommerce/product-searchform.php
Updates outdated template.
`siteorigin-unwind/woocommerce/product-searchform.php version 3.3.0 is out of date. The core version is 7.0.1,`
No changes are required for the search form so just a version bump.
=> Update WC Templates to 7.0.1
